# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5ff36e803707dce204ce0106fc992dec83822a44a2dea3d9f7755120eafe6244be01de0c72fbea6a65c60ede92bf184047141112e430cce91485bd3daa9a0d4e

test:
  secret_key_base: 9e2e95ae7a670aabb161385f02cd5e1e6c66cceddc548a6f7793904d054c1d13929c04e1b6adb6020c54a7471fc5f18d09f67aae4e766c64e3566d4cd66edc5d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
